Gpu swap prefetch
Sotskin/mxnet pull request #13
Opened 2018-06-25 14:58 UTC by KarlLeell

2018-06-28 14:35 UTC, fegin requested changes
Feel free to merge after you fix my reviews.

2018-06-28 14:35 UTC, fegin commented on include/mxnet/gpu_swap_prefetch.h
> +  bool begin_prefetching_;
"start" seems to be a better word than "begin". "start/stop".

2018-06-28 14:35 UTC, fegin commented on src/storage/gpu_swap_prefetch.cc
> +  begin_prefetching__ = false;
Two "_"? Typo?

2018-06-28 14:35 UTC, fegin commented on src/storage/gpu_swap_prefetch.cc
> +  while(stop_prefetching_) {
It seems that using one variable is enough, e.g., "is_running". But you may have a good reason to use two variables. If not, change to using one variable.

2018-06-28 22:49 UTC, fegin approved these changes

2018-06-28 22:49 UTC, fegin commented
Will do another code review sometime on Saturday.

2018-06-29 15:11 UTC, Sotskin requested changes
Just some style changes. Looks good

2018-06-29 15:11 UTC, Sotskin commented on include/mxnet/gpu_swap_history.h
> +  static const int NUMBER_OF_GPU = 8;
Why has number of gpu become static variable in MemHistory?

2018-06-29 15:11 UTC, Sotskin commented on include/mxnet/gpu_swap_prefetch.h
> +  std::vector<int> lookahead_pos = std::vector<int>(MemHistory::NUMBER_OF_GPU);
rename to lookahead_pos_

2018-06-29 18:09 UTC, qingsenzhang approved these changes

2018-06-30 14:53 UTC, fegin approved these changes

2018-06-30 15:44 UTC, Sotskin approved these changes

2018-07-02 15:27 UTC, merged