Update memory manager header file to avoid compiling error
Sotskin/mxnet pull request #14
Opened 2018-06-25 14:58 UTC by PhantomPhillipe

2018-06-25 18:01 UTC, Sotskin requested changes
Please add this API:
Get Memory Info: returns total memory and the biggest size of free memory that can be allocated at the time. (See  "cudaMemGetInfo")

2018-06-25 18:13 UTC, Sotskin requested changes

2018-06-25 18:13 UTC, Sotskin commented on include/mxnet/mem_mgr.h
> +    cudaError_t Memcpy(void* dst, const void* src, size_t count, enum cudaMemcpyKind kind);
Also, this function should take in the device id of gpu to copy to/from

2018-06-28 14:29 UTC, fegin requested changes
Feel free to merge after you fix my reviews.

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +const int FREELISTSIZE = 21;
FREE_LIST_SIZE. Without "_", it is not easy to read.

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +  idx = (idx > 19) ? 19 : idx;
19 is kind of a magic number. You should explain.

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +      , size_(size)
"," should be immediately after ")".

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +      , nextBlock_(NULL)
"," should be immediately after ")".

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +      , isFree_(true)
same here

2018-06-28 14:29 UTC, fegin commented on include/mxnet/mem_mgr.h
> +      , isHead_(false) {
and here

2018-06-28 19:01 UTC, merged