Segregated List MMU (In Progress)
Sotskin/mxnet pull request #19
Opened 2018-07-09 16:14 UTC by PhantomPhillipe

2018-07-13 17:10 UTC, fegin requested changes

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
> +const double GPUUTILRATIO = 0.95; //save some memory for each device(subject to change)
MINALLOCSIZE_-> MIN_ALLOC_SIZE
GPUUTILRATIO -> GPU_UTIL_RATIO

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
> +inline int getListIdx(size_t size) {
For the camel case naming, the first character of function names should be uppercase (Google coding style). Please change all functions.

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
> +  private:
Redundant private keyword.

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
> +  public:
Redundant public keyword.

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
> +  private:
Please group all private members together.

2018-07-13 17:10 UTC, fegin commented on include/mxnet/mem_mgr.h
>    private:
Please group all private members together.

2018-07-13 17:10 UTC, fegin commented on src/storage/mem_mgr.cc
> +        if (avail <= 0) break;
There should be a warning or assert message here.

2018-07-13 17:10 UTC, fegin commented on src/storage/mem_mgr.cc
> +    }
For completeness, you should also call cudaFree after this while.

2018-07-13 17:10 UTC, fegin commented on src/storage/mem_mgr.cc
>    CUDA_CALL(cudaSetDevice(deviceIdx));
Is this API call (cudaSetDevice) still needed?

2018-07-13 17:10 UTC, fegin commented on src/storage/mem_mgr.cc
> +  std::lock_guard<std::mutex> lock(mutex_);
Why do we need a mutex here? I believe cudaMemcpy is thread-safe.

2018-07-18 17:04 UTC, Sotskin commented
Looks good.

2018-07-18 17:04 UTC, Sotskin approved these changes

2018-07-24 19:20 UTC, fegin commented
Why do you merge this to gpu_swap_mem since you merge gpu_swap? gpu_swap_mem is apparently too old. So there are too many changes after you merged gpu_swap. Please close this pull request and create another pull request which will be directly merged to gpu_swap.

2018-07-24 19:20 UTC, closed without merging